#!/bin/bash
# Get the URL
REQUESTED=${REQUESTED#/page/}

# Check whether the file exists
make --dry-run "/mut/page-built/$REQUESTED" > /dev/null
if [ $? -eq 1 ]; then
	>&2 echo status 404
	exit 0
fi

make "/mut/page-built/$REQUESTED" > /dev/null

NAME=$(basename $REQUESTED)
EXTENSION="${NAME##*.}"

if [[ $EXTENSION == html ]]; then
	cat static/header.html
	echo "<title>$REQUESTED</title>"
	echo '</head><body>'
	cat "/mut/page-built/$REQUESTED"
	>&2 echo 'header Content-Type text/html'


	echo "
	<hr />
	<div class=\"hr\">
		<span>Alternate Formats</span>
	</div>
	"

	echo "<ul>"
	echo "<li>Listen: <audio controls src=\"/page/${REQUESTED%.html}.wav\" preload=\"none\"></audio></li>"
	echo "<li><a href=\"/page/${REQUESTED%.html}.pdf\">PDF</a></li>"
	echo "<li><a href=\"/page/${REQUESTED%.html}.epub\">EPUB</a></li>"
	echo "</ul>"

	echo "<p><i>Last modified on $(date -r page-src/${REQUESTED%.html})</i></p>"

	cat static/footer.html
else
	if [[ $EXTENSION == wav ]]; then 
		>&2 echo header Content-Type audio/wav
	fi
	cat "/mut/page-built/$REQUESTED"
fi